### ISSUE TITLE
Battery check

### ISSUE THREAD

**Issue by radeknh** [husarion/panther_driver#6]
https://github.com/husarion/panther_driver/blob/feature-adc-measurements-pb-1.2/panther_driver/src/driver_node.py#L277-L279
The 3,2V threshold (which equals the temperature of about -39*C) creates a risk of accidential "detecting" of the non-present battery because the base value is 3,3V with 2% tolerance of reference voltage and some tolerance of ADC and divider. The cumulated tolerance of about 8% should be considered, therefore the safe value for the threshold is 3,3V - 8% = 3,03V. This voltage is an equivalent of -22*C which is anyway close to the lower limit of the Panther working temperature range (-20*C).

**Comment by TopRamen1** [comment]
Thats a valid point to change that in the software. 
Changes have been made and a [PR](https://github.com/husarion/panther_driver/pull/9) is awaiting approval

**Comment by TopRamen1** [comment]
PR has been merged. Issue will be closed
